name: Feature Request
description: Suggest a new feature for Vestigo
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature for Vestigo! Please provide detailed information to help us understand and evaluate your request.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-flight Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and discussions to ensure this is not a duplicate
          required: true
        - label: I have read the [Contributing Guidelines](../CONTRIBUTING.md)
          required: true
        - label: This feature aligns with Vestigo's goals of firmware analysis and crypto-detection
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Backend API
        - Frontend UI
        - ML/GNN Models
        - Qiling Analysis
        - Ghidra Scripts
        - Protocol Analysis
        - Dynamic Analysis
        - Docker/Containerization
        - Documentation
        - CI/CD Pipeline
        - New Component
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Analysis Technique
        - New Cryptographic Algorithm Support
        - Performance Improvement
        - User Interface Enhancement
        - API Enhancement
        - New Architecture Support
        - Integration with External Tool
        - Documentation Improvement
        - Developer Experience
        - Security Enhancement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point does it address?
      placeholder: "Describe the problem or limitation this feature would address..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        Describe how you envision this feature working:
        - What would it do?
        - How would users interact with it?
        - What would be the expected output?
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases for this feature
      placeholder: |
        1. As a security researcher, I want to...
        2. When analyzing firmware from vendor X, I need to...
        3. During malware analysis, it would be helpful to...
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Target Users
      description: Who would primarily benefit from this feature?
      multiple: true
      options:
        - Security Researchers
        - Malware Analysts
        - Firmware Developers
        - Academic Researchers
        - Bug Bounty Hunters
        - IoT Security Teams
        - Reverse Engineers
        - Developers/Contributors
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Critical (Blocking current work)
        - High (Significantly improves workflow)
        - Medium (Nice to have improvement)
        - Low (Minor convenience)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered alternative solutions or workarounds?
      placeholder: |
        - Other tools that provide similar functionality
        - Current workarounds you're using
        - Different approaches to solving the same problem
    validations:
      required: false

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Implementation Details
      description: If you have technical insights, please share implementation ideas
      placeholder: |
        - Suggested libraries or frameworks
        - API design considerations
        - Database schema changes
        - Performance considerations
        - Security implications
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples and References
      description: Provide examples, mockups, or references to similar features
      placeholder: |
        - Links to similar features in other tools
        - Screenshots or mockups
        - Research papers or articles
        - Code examples or pseudocode
    validations:
      required: false

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (Few lines of code, no new dependencies)
        - Moderate (New module/component, some new dependencies)
        - Complex (Major architectural changes, significant new dependencies)
        - Very Complex (Requires extensive research, major system redesign)
        - Unknown
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Willingness
      description: Are you willing to contribute to this feature?
      options:
        - label: I can help with research and requirements gathering
          required: false
        - label: I can help with implementation (coding)
          required: false
        - label: I can help with testing
          required: false
        - label: I can help with documentation
          required: false
        - label: I can provide sample data or test cases
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, related issues, or relevant information
      placeholder: "Add any other context about the feature request here..."
    validations:
      required: false